### PR TITLE
Add support for midi `/key`, `/vel` and `/velocity`, use proper midiToFreq

### PR DESCRIPTION
**Pull request by spaskalev**

### CODE REVIEW

**Comment by sletz** [comment]
Possibly look at https://github.com/grame-cncm/faust/commit/7c4649f4192beb8d64c209750c1bd4d120588d92 ?

**Comment by spaskalev** [comment]
@sletz this fix seems to work for the demos here - check it out, I have added `poly-key.html` that plays different notes when mapped with `/key`

**Comment by sletz** [comment]
OK, but if you can report the alternate` /vel ` and `/velocity` code from https://github.com/grame-cncm/faust/commit/7c4649f4192beb8d64c209750c1bd4d120588d92, it would be even better !

**Comment by spaskalev** [comment]
Sure, let me try

**Comment by sletz** [comment]
Thanks  I'll test ASAP and then integrate it in Faust IDE.

**Comment by sletz** [comment]
Testing, I see an error in test/wpoly.html see the screenshot :
Capture d’écran 2022-04-29 à 07 47 08

I don't see how your change could explain that... do you see the same issue?

**Comment by spaskalev** [comment]
It's weird, bisecting commits with git shows that
```
e09a2eb38d9f96aecff659c121e023b94b62bf61 is the first bad commit
commit e09a2eb38d9f96aecff659c121e023b94b62bf61
Author: Stanislav Paskalev <spaskalev@vmware.com>
Date:   Fri Apr 29 00:02:14 2022 +0300

    Bump patch version

 dist/index.js         | 18 ++++++++++++++----
 dist/index.js.map     |  2 +-
 dist/index.min.js     |  2 +-
 dist/index.min.js.map |  2 +-
 package.json          |  2 +-
 5 files changed, 18 insertions(+), 8 deletions(-)

```

**Comment by spaskalev** [comment]
Looking at the minified code `this.fFreqLabel$.forEach((e=>this.factory.setParamValue(this.dspVoices$[n],e,i(t))))` it should be based on this this line

**Comment by spaskalev** [comment]
@sletz Got it, my ts/js is somewhat rusty :) It seems the const midifreq that I removed from there was just a prototype/declaration and not a definition.

Please run `npm run dist` and re-test. Thanks!

**Comment by spaskalev** [comment]
P.S. - I'd rather not push commits with the npm build deliverables, minified or not. This is a potential security issue, as they are hard to audit. Hence - just the fix.

**Comment by sletz** [comment]
"

> P.S. - I'd rather not push commits with the npm build deliverables, minified or not. This is a potential security issue, as they are hard to audit. Hence - just the fix.

Yes, I have the same feeling...

**Comment by sletz** [comment]
Thanks !

**Pull request merged**
